import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner/Banner";
import styles from "../styles/Home.module.scss";
import Hero from "../public/images/hero-image.png";
import Card from "../components/Card/Card";

export default function Home() {
  const handleOnClickBtnClick = () => {
    console.log("Button clicked");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={"View Stores Nearby"}
          handleOnClick={handleOnClickBtnClick}
        />
        <div className={styles.heroImage}>
          <Image src={Hero} alt="hero" />
        </div>
        <div className={styles.cardLayout}>
          <Card
            title="Coffee 1"
            image="/images/hero-image.png"
            href="/coffee-store/coffee-1"
            className={styles.card}
          />
          <Card
            title="Coffee 1"
            image="/images/hero-image.png"
            href="/coffee-store/coffee-1"
            className={styles.card}
          />
          <Card
            title="Coffee 1"
            image="/images/hero-image.png"
            href="/coffee-store/coffee-1"
            className={styles.card}
          />
          <Card
            title="Coffee 1"
            image="/images/hero-image.png"
            href="/coffee-store/coffee-1"
            className={styles.card}
          />
        </div>
      </main>
    </div>
  );
}
